contact_links:
  - name: "💬 Questions"
    url: https://github.com/OkutaniDaichi0106/moqrtc-js/discussions
    about: "Use Discussions for implementation and usage questions"

  - name: "📚 Documentation"
    url: https://okutanidaichi0106.github.io/moqrtc-js/
    about: "Project documentation"

  - name: "🔐 Security Report"
    url: https://github.com/OkutaniDaichi0106/moqrtc-js/security/advisories
    about: "Report security vulnerabilities directly"

  - name: "🤝 Contributing"
    url: https://github.com/OkutaniDaichi0106/moqrtc-js/blob/main/CONTRIBUTING.md
    about: "Please read our contributing guidelines"
